
if { [skip_fortran_tests] } { return -1 }

standard_testfile .f90
if { [prepare_for_testing ${testfile}.exp ${testfile} ${srcfile} {debug f90}] } {
    return -1
}


gdb_exit
gdb_start
gdb_reinitialize_dir $srcdir/$subdir
gdb_load ${binfile}

gdb_breakpoint [gdb_get_line_number "Breakpoint"]

gdb_start_cmd

gdb_continue_to_breakpoint "Continue to breakpoint"

gdb_test "print arr" "\\(\\( -2, -1, -1, -1, -1, -1, -1, -1, -1, -1\\) \\)"
gdb_test "print arr(5,4)" " = -3"
