# Copyright (C) 2026 Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# For an ELF that has no section called ".text" and the first section is
# non-alloc, test that a breakpoint can be set on a function.  This previously
# caused GDB to crash due to a missing null pointer check.

require is_elf_target

global srcdir
global subdir

standard_testfile

set linker_script $srcdir/$subdir/$testfile.ld

set options "debug ldscript=-Wl,-T${linker_script}"
if {[build_executable "failed to prepare" $testfile $srcfile $options]} {
    return -1
}

clean_restart $testfile

gdb_test "break main" "Breakpoint .* at .*"
