# Copyright 2026 Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Test that full symbol info is available to new_objfile observers.
#
# When on-demand debuginfo downloading completes, the new_objfile observer
# is notified about the separate debug objfile.  This test verifies that
# observers can access full symbol and type information at this point.
#
# The test registers a Python observer that looks up a symbol's type
# information when the separate debug objfile is loaded.

standard_testfile deferred-download.c \
    deferred-download-lib1.c \
    deferred-download-lib2.c

load_lib debuginfod-support.exp

require allow_debuginfod_tests
require allow_debuginfod_section_downloads

# BINFILE calls a function from LIB1_BINFILE.
set lib1_testfile "libdeferred1.so"
set lib1_srcfile $srcfile2
set lib1_binfile [standard_output_file $lib1_testfile]

# LIB1_BINFILE calls functions from LIB2_BINFILE.
set lib2_testfile "libdeferred2.so"
set lib2_srcfile $srcfile3
set lib2_binfile [standard_output_file $lib2_testfile]

# Build LIB1_BINFILE, LIB2_BINFILE, and BINFILE.
if { [build_executable "build $lib2_testfile" $lib2_binfile $lib2_srcfile \
	{debug build-id shlib}] } {
    return
}

if { [build_executable "build $lib1_testfile" $lib1_binfile $lib1_srcfile \
	[list debug build-id shlib_pthreads shlib=$lib2_binfile]] } {
    return
}

if { [build_executable "build executable" $binfile $srcfile \
	[list debug build-id shlib=$lib1_binfile shlib=$lib2_binfile]] } {
    return
}

# Start GDB now, we need GDB running in order to check the index types
# within the compiled executable and shared libraries.
clean_restart

# Add .gdb_index to the library.
if { [ensure_gdb_index $lib1_binfile "" "libdeferred1"] != 1 } {
    untested "failed to add .gdb_index to $lib1_testfile"
    return
}

# Strip debuginfo into a separate file.
if { [gdb_gnu_strip_debug $lib1_binfile ""] != 0 } {
    fail "strip $lib1_testfile debuginfo"
    return
}

# Move debuginfo file into a directory that debuginfod will serve.
set debugdir [standard_output_file "debug"]
set debuginfo_sl1 [standard_output_file $lib1_testfile.debug]

file mkdir $debugdir
file rename -force $debuginfo_sl1 $debugdir

# Python script that looks up type information from a new_objfile
# observer.
set pyscript [gdb_remote_download host ${srcdir}/${subdir}/${testfile}.py]

# Test that symbol type info is available in the observer.
proc_with_prefix test_deferred_status { } {
    global cache

    # Delete client cache so debuginfo downloads again.
    file delete -force $cache

    clean_restart

    gdb_test_no_output "set debuginfod enabled on"
    gdb_test_no_output "set progress-bars enabled off"

    # Load the Python script.
    gdb_test "source $::pyscript" "Python observer registered" \
	"load python script"

    gdb_load $::binfile

    gdb_breakpoint main
    gdb_run_cmd

    # During startup GDB adds the outline file for the debug
    # information for the shared library.  The new objfile observer
    # then kicks in and triggers the download of the full debug info,
    # and then prints some details relating to the newly downloaded
    # debug info.
    set saw_void_type false
    set saw_int_type false
    set saw_error false
    set saw_dbg_dl false
    gdb_test_multiple "" "run to main" -lbl {
	-re "\r\nDownloading \[^\r\n\]*separate debug info for \[^\r\n\]+${::lib1_testfile}\\.\\.\\.(?=\r\n)" {
	    set saw_dbg_dl true
	    exp_continue
	}
	-re "\r\nPython observer: found type void \\(\\)(?=\r\n)" {
	    set saw_void_type true
	    exp_continue
	}
	-re "\r\nPython observer: found type volatile int(?=\r\n)" {
	    set saw_int_type true
	    exp_continue
	}
	-re "\r\nPython observer: ERROR\[^\r\n\]+(?=\r\n)" {
	    set saw_error true
	    exp_continue
	}
	-re "\r\n$::gdb_prompt $" {
	    gdb_assert { $saw_dbg_dl && $saw_void_type && $saw_int_type \
			     && !$saw_error } $gdb_test_name
	}
    }

    # Step into the library.  Due to the new objfile observer
    # triggering the full debug info download earlier there should be
    # no additional debuginfod activity at this point.
    #
    # TODO: Maybe improve the pattern for the second line, we should
    # know the exact line we are stepping to at this point.
    gdb_test "step" \
	[multi_line \
	     "^libdeferred1_test \\(\\) at \[^\r\n\]+" \
	     "$::decimal\\s+\[^\r\n\]+"] \
	"step into library"
}

prepare_for_debuginfod cache db

with_debuginfod_env $cache {
    set url [start_debuginfod $db $debugdir]
    if { $url == "" } {
	unresolved "failed to start debuginfod server"
	return
    }

    setenv DEBUGINFOD_URLS $url
    test_deferred_status
}

stop_debuginfod
